---
stages:
  - test
  - release

.go_template_defaults:
  stage: test
include:
  - { project: fsrvcorp/templates, file: templates/language/go.yml, ref: 1.0.9 }

packages:
  stage: release
  image: goreleaser/goreleaser
  script:
    - goreleaser release --skip publish --snapshot --clean
  artifacts:
    paths:
      - dist/*.deb

deb mirror:
  stage: release
  image: alpine
  dependencies:
    - packages
  needs:
    - packages
  before_script:
    - apk add --no-cache ca-certificates curl
  script:
    - |
      for file in dist/*.deb; do
        URL="$(curl --upload-file ${file} https://t.fsrv.xyz)"
        curl -X POST --fail -F token=$CI_JOB_TOKEN -F "variables[PACKAGE_URL]=${URL}" -F ref=main https://ref.ci/api/v4/projects/185/trigger/pipeline
      done
