---
stages:
  - test
  - release

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
include:
  - project: fsrvcorp/templates
    file: templates/language/go.yml
    ref: 1.0.9
  - project: fsrvcorp/templates
    file: templates/release/semver.yml
    ref: 1.0.9

packages:
  stage: release
  image: goreleaser/goreleaser@sha256:123935a56bb422aee8c7eafd9c48868d03ffc84bc599eac28251a60ee393ac57
  script:
    - git reset --hard $CI_COMMIT_SHA
    - git clean -ffdx
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        goreleaser release --skip publish --clean
      else
        goreleaser release --skip publish --clean --snapshot
      fi
  artifacts:
    paths:
      - dist/*.deb

deb mirror:
  stage: release
  image: alpine@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a
  only:
    - tags
  dependencies:
    - packages
  needs:
    - packages
  before_script:
    - apk add --no-cache ca-certificates curl
  script:
    - |
      for file in dist/*.deb; do
        URL="$(curl --upload-file ${file} https://t.fsrv.xyz)"
        curl -X POST --fail -F token=$CI_JOB_TOKEN -F "variables[PACKAGE_URL]=${URL}" -F ref=main https://ref.ci/api/v4/projects/185/trigger/pipeline
      done
