---
stages:
  - test
  - release

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
include:
  - project: fsrvcorp/templates
    file: templates/language/go.yml
    ref: 1.0.9
  - project: fsrvcorp/templates
    file: templates/release/semver.yml
    ref: 1.0.9

packages:
  stage: release
  image: goreleaser/goreleaser@sha256:d62b4a18dfe3af7bd4da9e5954b496548ef04e73ae8f98cd75ba63a9ed4d73e5
  script:
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        goreleaser release --skip publish --clean
      else
        goreleaser release --skip publish --clean --snapshot
      fi
  artifacts:
    paths:
      - dist/*.deb

deb mirror:
  stage: release
  image: alpine@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d
  only:
    - tags
  dependencies:
    - packages
  needs:
    - packages
  before_script:
    - apk add --no-cache ca-certificates curl
  script:
    - |
      for file in dist/*.deb; do
        URL="$(curl --upload-file ${file} https://t.fsrv.xyz)"
        curl -X POST --fail -F token=$CI_JOB_TOKEN -F "variables[PACKAGE_URL]=${URL}" -F ref=main https://ref.ci/api/v4/projects/185/trigger/pipeline
      done
