version: 2

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goarch:
      - amd64
      - arm64
    goos:
      - linux

nfpms:
  - maintainer: "Florian Bauer"
    formats:
      - deb
    scripts:
      postinstall: ./init/postinstall.sh
    contents:
      - src: ./init/bird-flowspec-daemon.service
        dst: /etc/systemd/system/bird-flowspec-daemon.service
        type: config
